USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;



CREATE DATABASE IF NOT EXISTS STREAMLIT_DEMO_DB;
CREATE SCHEMA IF NOT EXISTS STREAMLIT_DEMO_DB.APPS;

USE DATABASE STREAMLIT_DEMO_DB;
USE SCHEMA APPS;




CREATE OR REPLACE STREAMLIT my_first_app
    QUERY_WAREHOUSE = COMPUTE_WH
    TITLE = 'My First Streamlit App'
    COMMENT = 'SnowPro Core 学習用';


show streamlits;

DESC STREAMLIT my_first_app;


-- 別の WH に変更
ALTER STREAMLIT my_first_app SET
    QUERY_WAREHOUSE = COMPUTE_WH
    COMMENT = '更新したコメント';

-- タイトルだけ変更
ALTER STREAMLIT my_first_app SET TITLE = 'タイトル変更テスト';

-- リネーム
ALTER STREAMLIT my_first_app RENAME TO my_first_app_v2;

-- 確認
SHOW STREAMLITS;

-- 元に戻す
ALTER STREAMLIT my_first_app_v2 RENAME TO my_first_app;


-- テスト用の role を作る
CREATE ROLE IF NOT EXISTS STREAMLIT_VIEWER_ROLE;
GRANT ROLE STREAMLIT_VIEWER_ROLE TO USER SZKOU22;


select current_user();



-- USAGE 権限を grant
GRANT USAGE ON DATABASE STREAMLIT_DEMO_DB TO ROLE STREAMLIT_VIEWER_ROLE;
GRANT USAGE ON SCHEMA   STREAMLIT_DEMO_DB.APPS TO ROLE STREAMLIT_VIEWER_ROLE;
GRANT USAGE ON STREAMLIT STREAMLIT_DEMO_DB.APPS.my_first_app
TO ROLE STREAMLIT_VIEWER_ROLE;



// クリーンアップ

USE ROLE ACCOUNTADMIN;

DROP STREAMLIT IF EXISTS STREAMLIT_DEMO_DB.APPS.my_first_app;
DROP ROLE IF EXISTS STREAMLIT_VIEWER_ROLE;
DROP DATABASE IF EXISTS STREAMLIT_DEMO_DB;





    